/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as ArtistsSlugRouteImport } from './routes/artists/$slug'
import { Route as CorpusIndexRouteImport } from './routes/corpus/index'
import { Route as CorpusIssueRouteImport } from './routes/corpus/$issue'
import { Route as CorrespondencesIndexRouteImport } from './routes/correspondences/index'
import { Route as EventsSlugRouteImport } from './routes/events/$slug'
import { Route as PlacesSlugRouteImport } from './routes/places/$slug'
import { Route as ProvisionsIndexRouteImport } from './routes/provisions/index'
import { Route as ProvisionsSlugRouteImport } from './routes/provisions/$slug'
import { Route as ResidueIndexRouteImport } from './routes/residue/index'
import { Route as ResidueSlugRouteImport } from './routes/residue/$slug'
import { Route as TheoryIndexRouteImport } from './routes/theory/index'
import { Route as TheorySlugRouteImport } from './routes/theory/$slug'
import { Route as WorkIndexRouteImport } from './routes/work/index'
import { Route as WorkSlugRouteImport } from './routes/work/$slug'
import { Route as CorpusIssueArticleRouteImport } from './routes/corpus/$issue.$article'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsSlugRoute = ArtistsSlugRouteImport.update({
  id: '/artists/$slug',
  path: '/artists/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CorpusIndexRoute = CorpusIndexRouteImport.update({
  id: '/corpus/',
  path: '/corpus/',
  getParentRoute: () => rootRouteImport,
} as any)
const CorpusIssueRoute = CorpusIssueRouteImport.update({
  id: '/corpus/$issue',
  path: '/corpus/$issue',
  getParentRoute: () => rootRouteImport,
} as any)
const CorrespondencesIndexRoute = CorrespondencesIndexRouteImport.update({
  id: '/correspondences/',
  path: '/correspondences/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/events/$slug',
  path: '/events/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacesSlugRoute = PlacesSlugRouteImport.update({
  id: '/places/$slug',
  path: '/places/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvisionsIndexRoute = ProvisionsIndexRouteImport.update({
  id: '/provisions/',
  path: '/provisions/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvisionsSlugRoute = ProvisionsSlugRouteImport.update({
  id: '/provisions/$slug',
  path: '/provisions/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ResidueIndexRoute = ResidueIndexRouteImport.update({
  id: '/residue/',
  path: '/residue/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResidueSlugRoute = ResidueSlugRouteImport.update({
  id: '/residue/$slug',
  path: '/residue/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TheoryIndexRoute = TheoryIndexRouteImport.update({
  id: '/theory/',
  path: '/theory/',
  getParentRoute: () => rootRouteImport,
} as any)
const TheorySlugRoute = TheorySlugRouteImport.update({
  id: '/theory/$slug',
  path: '/theory/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkIndexRoute = WorkIndexRouteImport.update({
  id: '/work/',
  path: '/work/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkSlugRoute = WorkSlugRouteImport.update({
  id: '/work/$slug',
  path: '/work/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CorpusIssueArticleRoute = CorpusIssueArticleRouteImport.update({
  id: '/$article',
  path: '/$article',
  getParentRoute: () => CorpusIssueRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/artists/$slug': typeof ArtistsSlugRoute
  '/corpus/$issue': typeof CorpusIssueRouteWithChildren
  '/events/$slug': typeof EventsSlugRoute
  '/places/$slug': typeof PlacesSlugRoute
  '/provisions/$slug': typeof ProvisionsSlugRoute
  '/residue/$slug': typeof ResidueSlugRoute
  '/theory/$slug': typeof TheorySlugRoute
  '/work/$slug': typeof WorkSlugRoute
  '/corpus/': typeof CorpusIndexRoute
  '/correspondences/': typeof CorrespondencesIndexRoute
  '/provisions/': typeof ProvisionsIndexRoute
  '/residue/': typeof ResidueIndexRoute
  '/theory/': typeof TheoryIndexRoute
  '/work/': typeof WorkIndexRoute
  '/corpus/$issue/$article': typeof CorpusIssueArticleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/artists/$slug': typeof ArtistsSlugRoute
  '/corpus/$issue': typeof CorpusIssueRouteWithChildren
  '/events/$slug': typeof EventsSlugRoute
  '/places/$slug': typeof PlacesSlugRoute
  '/provisions/$slug': typeof ProvisionsSlugRoute
  '/residue/$slug': typeof ResidueSlugRoute
  '/theory/$slug': typeof TheorySlugRoute
  '/work/$slug': typeof WorkSlugRoute
  '/corpus': typeof CorpusIndexRoute
  '/correspondences': typeof CorrespondencesIndexRoute
  '/provisions': typeof ProvisionsIndexRoute
  '/residue': typeof ResidueIndexRoute
  '/theory': typeof TheoryIndexRoute
  '/work': typeof WorkIndexRoute
  '/corpus/$issue/$article': typeof CorpusIssueArticleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/artists/$slug': typeof ArtistsSlugRoute
  '/corpus/$issue': typeof CorpusIssueRouteWithChildren
  '/events/$slug': typeof EventsSlugRoute
  '/places/$slug': typeof PlacesSlugRoute
  '/provisions/$slug': typeof ProvisionsSlugRoute
  '/residue/$slug': typeof ResidueSlugRoute
  '/theory/$slug': typeof TheorySlugRoute
  '/work/$slug': typeof WorkSlugRoute
  '/corpus/': typeof CorpusIndexRoute
  '/correspondences/': typeof CorrespondencesIndexRoute
  '/provisions/': typeof ProvisionsIndexRoute
  '/residue/': typeof ResidueIndexRoute
  '/theory/': typeof TheoryIndexRoute
  '/work/': typeof WorkIndexRoute
  '/corpus/$issue/$article': typeof CorpusIssueArticleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/artists/$slug'
    | '/corpus/$issue'
    | '/events/$slug'
    | '/places/$slug'
    | '/provisions/$slug'
    | '/residue/$slug'
    | '/theory/$slug'
    | '/work/$slug'
    | '/corpus/'
    | '/correspondences/'
    | '/provisions/'
    | '/residue/'
    | '/theory/'
    | '/work/'
    | '/corpus/$issue/$article'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/artists/$slug'
    | '/corpus/$issue'
    | '/events/$slug'
    | '/places/$slug'
    | '/provisions/$slug'
    | '/residue/$slug'
    | '/theory/$slug'
    | '/work/$slug'
    | '/corpus'
    | '/correspondences'
    | '/provisions'
    | '/residue'
    | '/theory'
    | '/work'
    | '/corpus/$issue/$article'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/artists/$slug'
    | '/corpus/$issue'
    | '/events/$slug'
    | '/places/$slug'
    | '/provisions/$slug'
    | '/residue/$slug'
    | '/theory/$slug'
    | '/work/$slug'
    | '/corpus/'
    | '/correspondences/'
    | '/provisions/'
    | '/residue/'
    | '/theory/'
    | '/work/'
    | '/corpus/$issue/$article'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  ArtistsSlugRoute: typeof ArtistsSlugRoute
  CorpusIssueRoute: typeof CorpusIssueRouteWithChildren
  EventsSlugRoute: typeof EventsSlugRoute
  PlacesSlugRoute: typeof PlacesSlugRoute
  ProvisionsSlugRoute: typeof ProvisionsSlugRoute
  ResidueSlugRoute: typeof ResidueSlugRoute
  TheorySlugRoute: typeof TheorySlugRoute
  WorkSlugRoute: typeof WorkSlugRoute
  CorpusIndexRoute: typeof CorpusIndexRoute
  CorrespondencesIndexRoute: typeof CorrespondencesIndexRoute
  ProvisionsIndexRoute: typeof ProvisionsIndexRoute
  ResidueIndexRoute: typeof ResidueIndexRoute
  TheoryIndexRoute: typeof TheoryIndexRoute
  WorkIndexRoute: typeof WorkIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists/$slug': {
      id: '/artists/$slug'
      path: '/artists/$slug'
      fullPath: '/artists/$slug'
      preLoaderRoute: typeof ArtistsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corpus/': {
      id: '/corpus/'
      path: '/corpus'
      fullPath: '/corpus/'
      preLoaderRoute: typeof CorpusIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corpus/$issue': {
      id: '/corpus/$issue'
      path: '/corpus/$issue'
      fullPath: '/corpus/$issue'
      preLoaderRoute: typeof CorpusIssueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/correspondences/': {
      id: '/correspondences/'
      path: '/correspondences'
      fullPath: '/correspondences/'
      preLoaderRoute: typeof CorrespondencesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/events/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/places/$slug': {
      id: '/places/$slug'
      path: '/places/$slug'
      fullPath: '/places/$slug'
      preLoaderRoute: typeof PlacesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provisions/': {
      id: '/provisions/'
      path: '/provisions'
      fullPath: '/provisions/'
      preLoaderRoute: typeof ProvisionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provisions/$slug': {
      id: '/provisions/$slug'
      path: '/provisions/$slug'
      fullPath: '/provisions/$slug'
      preLoaderRoute: typeof ProvisionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/residue/': {
      id: '/residue/'
      path: '/residue'
      fullPath: '/residue/'
      preLoaderRoute: typeof ResidueIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/residue/$slug': {
      id: '/residue/$slug'
      path: '/residue/$slug'
      fullPath: '/residue/$slug'
      preLoaderRoute: typeof ResidueSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/theory/': {
      id: '/theory/'
      path: '/theory'
      fullPath: '/theory/'
      preLoaderRoute: typeof TheoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/theory/$slug': {
      id: '/theory/$slug'
      path: '/theory/$slug'
      fullPath: '/theory/$slug'
      preLoaderRoute: typeof TheorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/': {
      id: '/work/'
      path: '/work'
      fullPath: '/work/'
      preLoaderRoute: typeof WorkIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/$slug': {
      id: '/work/$slug'
      path: '/work/$slug'
      fullPath: '/work/$slug'
      preLoaderRoute: typeof WorkSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corpus/$issue/$article': {
      id: '/corpus/$issue/$article'
      path: '/$article'
      fullPath: '/corpus/$issue/$article'
      preLoaderRoute: typeof CorpusIssueArticleRouteImport
      parentRoute: typeof CorpusIssueRoute
    }
  }
}

interface CorpusIssueRouteChildren {
  CorpusIssueArticleRoute: typeof CorpusIssueArticleRoute
}

const CorpusIssueRouteChildren: CorpusIssueRouteChildren = {
  CorpusIssueArticleRoute: CorpusIssueArticleRoute,
}

const CorpusIssueRouteWithChildren = CorpusIssueRoute._addFileChildren(
  CorpusIssueRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  ArtistsSlugRoute: ArtistsSlugRoute,
  CorpusIssueRoute: CorpusIssueRouteWithChildren,
  EventsSlugRoute: EventsSlugRoute,
  PlacesSlugRoute: PlacesSlugRoute,
  ProvisionsSlugRoute: ProvisionsSlugRoute,
  ResidueSlugRoute: ResidueSlugRoute,
  TheorySlugRoute: TheorySlugRoute,
  WorkSlugRoute: WorkSlugRoute,
  CorpusIndexRoute: CorpusIndexRoute,
  CorrespondencesIndexRoute: CorrespondencesIndexRoute,
  ProvisionsIndexRoute: ProvisionsIndexRoute,
  ResidueIndexRoute: ResidueIndexRoute,
  TheoryIndexRoute: TheoryIndexRoute,
  WorkIndexRoute: WorkIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
